### ISSUE TITLE
Add software-based equalizer

### ISSUE THREAD

**Issue by jcass77** [pimusicbox/pimusicbox#306] opened 2015-07-25 04:14 UTC
It might be a useful if Musicbox included an equalizer of sorts that would allow users to adjust the frequency profile to match their personal tastes.

**Comment by jcass77** [comment] 2015-08-14 16:13
Just a note that I've been using the equalisation functionality for the last month or so. It seems to be working well and has greatly improved the listening enjoyment of a pair of small Boston Acoustic A23 speakers that I am running off a HiFiBerry Amp+.

**Comment by kingosticks** [comment] 2015-08-14 17:32
OK great, I will take another look at it in next few days when I get a chance.

**Comment by jodal** [comment] 2015-08-31 21:35
I think this is enough of a duplicate of #137 to close it.

**Closed by jodal** 2015-08-31 21:35 UTC
Labels: enhancement
