### ISSUE TITLE
UI Stuck on"Trying to Reach Musicbox. Please Wait"

### ISSUE THREAD

**Issue by HalfAdd3r** [pimusicbox/pimusicbox#117] opened 2014-07-16 05:22 UTC
GUI seems to not move past trying to load data.  Interface continues to run "Trying to Reach.." message. The same is true in multiple browsers.  

Possibly related: System commands (Restart, Shutdown) just return to main Index.html without affecting system.  

Please let me know what logs/data would be useful for troubleshooting.

![capture](https://cloud.githubusercontent.com/assets/2043487/3594887/131e2f04-0ca9-11e4-9063-fa74ae2127a6.JPG)

**Comment by driesken** [comment] 2015-01-09 06:06
I'm also having this issue on MusicBox 0.5.2. I'm on a wired connection though. Most musicplugins for external services have been disabled.

**Comment by tias79** [comment] 2015-01-26 10:29
I've had this issue since 0.5.0 and it is still present in 0.5.3. I've all services turned off except "Spotify" and "Local files".

[UTC Jan 26 10:27:40] error    : 'mopidy' failed, cannot open a connection to INET[localhost:6680] via TCP
[UTC Jan 26 10:27:40] info     : 'mopidy' trying to restart
[UTC Jan 26 10:27:40] info     : 'mopidy' stop: /etc/init.d/mopidy
[UTC Jan 26 10:27:41] info     : 'mopidy' start: /etc/init.d/mopidy

**Comment by kingosticks** [comment] 2015-01-26 13:05
So in your logs, monit decides mopidy is not responding (it possibly needed to wait a bit longer before checking) and restarts it. And then Mopidy tries to start again but the log ends, is there nothing 

Does it work if you turn off everything?

**Comment by tias79** [comment] 2015-01-29 23:27
I tried disabling "Local files" and "Spotify" as well (so that all services
are disabled), but I still seem to get the same stuff in the log after a
while.

Mattias

**Comment by tias79** [comment] 2015-04-08 18:32
Knock on wood, but I don't seem to have this issue in 0.6.0!

**Comment by jodal** [comment] 2015-08-31 21:47
Issue has multiple causes, directed to the forum a year ago, about zero activity this year. Closing.

**Closed by jodal** 2015-08-31 21:47 UTC

**Comment by mauli16** [comment] 2018-11-10 23:37
The issue is still there for me. I tested it on a raspberry 1 and on a raspberry 3 b+ with the newest RC-version. Musicbox runs fine for approximately 24h, but after that it's broken. My wifi is off over night. Maybe that's the problem? I deactivated unnecessary plugins too. Don't know what I can do. Is there another raspi mpd-project with soundcloud support? thx
