### ISSUE TITLE
librespot crashes.

### ISSUE THREAD

**Issue by gibman** [pimusicbox/pimusicbox#503] opened 2018-11-06 10:11 UTC
running 0.7.0 rc6

sudo opt/librespot/librespot -n kitchen -u *** -p *** -b 320 --onevent /opt/musicbox/mpc_stop.sh --device-type speaker

results in =>

INFO:librespot: librespot 9d9c311 (2018-03-11). Built on 2018-03-13. Build ID: BECir1hc
INFO:librespot_core::session: Connecting to AP "gew1-accesspoint-b-jq02.ap.spotify.com:4070"
INFO:librespot_core::session: Authenticated as "*****" !
INFO:librespot_core::session: Country: "**"
INFO:librespot_playback::audio_backend::alsa: Using alsa sink
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError(InvalidEnumValue(14))', /checkout/src/libcore/result.rs:916:5
stack backtrace:
   0:   0x89463f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h280c621ec0336843
                       at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:   0x89e89b - std::sys_common::backtrace::print::h5bb167d48668dac9
                       at /checkout/src/libstd/sys_common/backtrace.rs:68
                       at /checkout/src/libstd/sys_common/backtrace.rs:57
   2:   0x88cec7 - std::panicking::default_hook::{{closure}}::hccf3b2e1cc48596f
                       at /checkout/src/libstd/panicking.rs:381
   3:   0x88c9a3 - std::panicking::default_hook::h338b1189515ccc69
                       at /checkout/src/libstd/panicking.rs:397
   4:   0x88d373 - std::panicking::rust_panic_with_hook::h5d950fb4a856fba5
                       at /checkout/src/libstd/panicking.rs:577
   5:   0x88d217 - std::panicking::begin_panic::h7a5157aecf168062
                       at /checkout/src/libstd/panicking.rs:538
   6:   0x88d143 - std::panicking::begin_panic_fmt::hc44606ee40e9a98e
                       at /checkout/src/libstd/panicking.rs:522
   7:   0x88d0eb - rust_begin_unwind
                       at /checkout/src/libstd/panicking.rs:498
   8:   0x8f61a3 - core::panicking::panic_fmt::h68e7715928be641f
                       at /checkout/src/libcore/panicking.rs:71
   9:   0x50cccb - core::result::unwrap_failed::hc8e405a7d6f5e105
  10:   0x4e578b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once::h550fb1c59c949344
  11:   0x50450f - <futures::stream::map::Map<S, F> as futures::stream::Stream>::poll::h6f4042a85363f6fe
  12:   0x4ef1c3 - <librespot_connect::spirc::SpircTask as futures::future::Future>::poll::h2ae68a0a355e9093
  13:   0x477fdf - <librespot::Main as futures::future::Future>::poll::ha34952329266c131
  14:   0x47061f - futures::task_impl::std::set::haa73a9ee0a468b94
  15:   0x488f8b - tokio_core::reactor::Core::run::h8b40cb76d6ebd0af
  16:   0x479aa3 - librespot::main::hf84f741837bd497f
  17:   0x489a13 - std::rt::lang_start::{{closure}}::h369662dc239e3883
  18:   0x88d01b - std::panicking::try::do_call::h9cb586bd57bb9d3d
                       at /checkout/src/libstd/rt.rs:59
                       at /checkout/src/libstd/panicking.rs:480
  19:   0x8b3c33 - __rust_maybe_catch_panic
                       at /checkout/src/libpanic_unwind/lib.rs:101
  20:   0x8942cb - std::rt::lang_start_internal::h104139376fdb9ead
                       at /checkout/src/libstd/panicking.rs:459
                       at /checkout/src/libstd/panic.rs:365
                       at /checkout/src/libstd/rt.rs:58
  21:   0x47a583 - main
  22: 0xb6d6381b - __libc_start_main

--- I updated to latest raspotify 0.11.5

# Install curl and https apt transport
sudo apt-get -y install curl apt-transport-https

# Add repo and its GPG key
curl -sSL https://dtcooper.github.io/raspotify/key.asc | sudo apt-key add -v -
echo 'deb https://dtcooper.github.io/raspotify jessie main' | sudo tee /etc/apt/sources.list.d/raspotify.list

# Install package
sudo apt-get update
sudo apt-get -y install raspotify

#overwrite librespot with raspotify
pkill librespot
sudo copy /usr/bin/librespot /opt/librespot/librespot

sudo reboot

seems to work better :)

Maybe you should update the image to  raspotify 0.11.5 instead of the deprecated librespot ?

**Comment by kingosticks** [comment] 2018-11-06 10:37
What makes you think librespot is deprecated? Raspotify is literally a Debian package of librespot. All the work (some of which is my own) is from the very much alive librespot project. 

And this is a duplicate of https://github.com/pimusicbox/pimusicbox/issues/480

**Closed by kingosticks** 2018-11-06 10:37 UTC
